/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as GeographyRouteImport } from './routes/geography'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as WarehousesRouteImport } from './routes/warehouses'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as ItemsIndexRouteImport } from './routes/items.index'
import { Route as ItemsIdRouteImport } from './routes/items.$id'
import { Route as SuppliersIndexRouteImport } from './routes/suppliers.index'
import { Route as SuppliersIdRouteImport } from './routes/suppliers.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const GeographyRoute = GeographyRouteImport.update({
  id: '/geography',
  path: '/geography',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehousesRoute = WarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIndexRoute = ItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIdRoute = ItemsIdRouteImport.update({
  id: '/items/$id',
  path: '/items/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIndexRoute = SuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIdRoute = SuppliersIdRouteImport.update({
  id: '/suppliers/$id',
  path: '/suppliers/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/employees': typeof EmployeesRoute
  '/geography': typeof GeographyRoute
  '/vehicles': typeof VehiclesRoute
  '/warehouses': typeof WarehousesRoute
  '/customers/$id': typeof CustomersIdRoute
  '/items/$id': typeof ItemsIdRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/items/': typeof ItemsIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/employees': typeof EmployeesRoute
  '/geography': typeof GeographyRoute
  '/vehicles': typeof VehiclesRoute
  '/warehouses': typeof WarehousesRoute
  '/customers/$id': typeof CustomersIdRoute
  '/items/$id': typeof ItemsIdRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/customers': typeof CustomersIndexRoute
  '/items': typeof ItemsIndexRoute
  '/suppliers': typeof SuppliersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/employees': typeof EmployeesRoute
  '/geography': typeof GeographyRoute
  '/vehicles': typeof VehiclesRoute
  '/warehouses': typeof WarehousesRoute
  '/customers/$id': typeof CustomersIdRoute
  '/items/$id': typeof ItemsIdRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/items/': typeof ItemsIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/employees'
    | '/geography'
    | '/vehicles'
    | '/warehouses'
    | '/customers/$id'
    | '/items/$id'
    | '/suppliers/$id'
    | '/customers/'
    | '/items/'
    | '/suppliers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/employees'
    | '/geography'
    | '/vehicles'
    | '/warehouses'
    | '/customers/$id'
    | '/items/$id'
    | '/suppliers/$id'
    | '/customers'
    | '/items'
    | '/suppliers'
  id:
    | '__root__'
    | '/'
    | '/employees'
    | '/geography'
    | '/vehicles'
    | '/warehouses'
    | '/customers/$id'
    | '/items/$id'
    | '/suppliers/$id'
    | '/customers/'
    | '/items/'
    | '/suppliers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmployeesRoute: typeof EmployeesRoute
  GeographyRoute: typeof GeographyRoute
  VehiclesRoute: typeof VehiclesRoute
  WarehousesRoute: typeof WarehousesRoute
  CustomersIdRoute: typeof CustomersIdRoute
  ItemsIdRoute: typeof ItemsIdRoute
  SuppliersIdRoute: typeof SuppliersIdRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  ItemsIndexRoute: typeof ItemsIndexRoute
  SuppliersIndexRoute: typeof SuppliersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geography': {
      id: '/geography'
      path: '/geography'
      fullPath: '/geography'
      preLoaderRoute: typeof GeographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouses': {
      id: '/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof WarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/': {
      id: '/items/'
      path: '/items'
      fullPath: '/items/'
      preLoaderRoute: typeof ItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$id': {
      id: '/items/$id'
      path: '/items/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof ItemsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/': {
      id: '/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof SuppliersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/$id': {
      id: '/suppliers/$id'
      path: '/suppliers/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof SuppliersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmployeesRoute: EmployeesRoute,
  GeographyRoute: GeographyRoute,
  VehiclesRoute: VehiclesRoute,
  WarehousesRoute: WarehousesRoute,
  CustomersIdRoute: CustomersIdRoute,
  ItemsIdRoute: ItemsIdRoute,
  SuppliersIdRoute: SuppliersIdRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  ItemsIndexRoute: ItemsIndexRoute,
  SuppliersIndexRoute: SuppliersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
